name: Deploy to Cloud Storage using Google Cloud SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # - name: Configure Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.5.0
      #   with:
      #     project_id: learngcp-418900
      #     service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloud Storage
        run: |
          gsutil -m cp -r build/* gs://my-react-app12121

      - name: Post Deployment Cleanup
        run: |
          # Cleaning up after deployment
